modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT License"
issueTrackerURL = "https://bumblecat.dev/issues/foodsicles"

[[mods]]
    modId = "foodsicles"
    version = "${file.jarVersion}"
    displayName = "Foodsicles"
    updateJSONURL = "https://bumblecat.dev/version/foodsicles"
    displayURL = "https://bumblecat.dev/"
    logoFile = "foodsicles.png"
    authors = "Baijson"
    description = ''' Your regular dose of nutrition.. ON A STICK!! '''

[[dependencies.foodsicles]]
    modId = "forge"
    mandatory = true
    versionRange = "[39,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.foodsicles]]
    modId = "bumblecore"
    mandatory = true
    versionRange = "[1.0.5,)"
    ordering = "AFTER"
    side = "BOTH"